name: hdf5 dev daily build

# Triggers the workflow on demand or on a call from another workflow
# NOTE: inputs must be duplicated between triggers
on:
  workflow_dispatch:
    inputs:
      use_ignore:
        description: 'Ignore has_changes check'
        type: string
        required: false
        default: check
  workflow_call:
    inputs:
      use_ignore:
        description: 'Ignore has_changes check'
        type: string
        required: false
        default: check
    outputs:
      has_changes:
        description: "Whether there were changes the previous day"
        value: ${{ jobs.call-workflow-tarball.outputs.has_changes }}
      file_base:
        description: "The common base name of the source tarballs"
        value: ${{ jobs.call-workflow-tarball.outputs.file_base }}

permissions:
  contents: read

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  get-old-names:
    runs-on: ubuntu-latest
    outputs:
      hdf5-name: ${{ steps.gethdf5base.outputs.HDF5_NAME_BASE }}
      run-ignore: ${{ steps.getinputs.outputs.INPUTS_IGNORE }}

    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Get hdf5 release base name
      uses: dsaltares/fetch-gh-release-asset@aa2ab1243d6e0d5b405b973c89fa4d06a2d0fff7 # master
      with:
        version: 'tags/snapshot'
        file: 'last-file.txt'
      continue-on-error: true

    - name: Read base-name file
      id: gethdf5base
      run: echo "HDF5_NAME_BASE=$(cat last-file.txt)" >> $GITHUB_OUTPUT

    - run: echo "hdf5 base name is ${{ steps.gethdf5base.outputs.HDF5_NAME_BASE }}."

    - name: Read inputs
      id: getinputs
      run: |
        echo "INPUTS_IGNORE=${{ inputs.use_ignore }}" >> $GITHUB_OUTPUT

    - run: echo "use_ignore is ${{ steps.getinputs.outputs.INPUTS_IGNORE }}."

  call-workflow-tarball:
    needs: [get-old-names]
    uses: ./.github/workflows/tarball.yml
    with:
      use_ignore: ${{ needs.get-old-names.outputs.run-ignore }}
      use_tag: snapshot
      use_environ: snapshots

  call-aws-c-s3-build:
    needs: call-workflow-tarball
    name: "Build aws-c-s3 library"
    uses: ./.github/workflows/build-aws-c-s3.yml
    with:
      build_mode: "Release"
      # Use latest release for building from source on Ubuntu
      # until a package is available to install
      aws_c_s3_tag: "v0.8.0"
    if: ${{ ((needs.call-workflow-tarball.outputs.has_changes == 'true') || (needs.get-old-names.outputs.run-ignore == 'ignore')) }}

  call-release-cmake-cygwin:
    needs: [get-old-names, call-workflow-tarball]
    name: "Cygwin Workflows"
    uses: ./.github/workflows/cygwin.yml
    with:
      file_base: ${{ needs.call-workflow-tarball.outputs.file_base }}
      use_environ: snapshots
    if: ${{ ((needs.call-workflow-tarball.outputs.has_changes == 'true') || (needs.get-old-names.outputs.run-ignore == 'ignore')) }}

  call-workflow-c-script:
    needs: [get-old-names, call-workflow-tarball, call-aws-c-s3-build]
    uses: ./.github/workflows/script.yml
    with:
      cmake_version: "latest"
      file_base: ${{ needs.call-workflow-tarball.outputs.file_base }}
      use_environ: snapshots
    if: ${{ ((needs.call-workflow-tarball.outputs.has_changes == 'true') || (needs.get-old-names.outputs.run-ignore == 'ignore')) }}

  call-workflow-par-script:
    needs: [get-old-names, call-workflow-tarball]
    uses: ./.github/workflows/par-script.yml
    with:
      cmake_version: "latest"
      file_base: ${{ needs.call-workflow-tarball.outputs.file_base }}
      use_environ: snapshots
      build_mode: "Release"
    if: ${{ ((needs.call-workflow-tarball.outputs.has_changes == 'true') || (needs.get-old-names.outputs.run-ignore == 'ignore')) }}

  call-workflow-par-source:
    needs: [get-old-names, call-workflow-tarball]
    uses: ./.github/workflows/par-source.yml
    with:
      cmake_version: "latest"
      file_base: ${{ needs.call-workflow-tarball.outputs.file_base }}
      use_environ: snapshots
      build_mode: "Release"
    if: ${{ ((needs.call-workflow-tarball.outputs.has_changes == 'true') || (needs.get-old-names.outputs.run-ignore == 'ignore')) }}

  call-developer-cmake:
    needs: [get-old-names, call-workflow-tarball]
    name: "Developer Workflows"
    uses: ./.github/workflows/dev.yml
    with:
      file_base: ${{ needs.call-workflow-tarball.outputs.file_base }}
    if: ${{ ((needs.call-workflow-tarball.outputs.has_changes == 'true') || (needs.get-old-names.outputs.run-ignore == 'ignore')) }}

  call-workflow-sanitizers:
    needs: [get-old-names, call-workflow-tarball]
    uses: ./.github/workflows/analysis.yml
    with:
      file_base: ${{ needs.call-workflow-tarball.outputs.file_base }}
      use_environ: snapshots
    if: ${{ ((needs.call-workflow-tarball.outputs.has_changes == 'true') || (needs.get-old-names.outputs.run-ignore == 'ignore')) }}

  call-workflow-ctest:
    needs: [get-old-names, call-workflow-tarball, call-aws-c-s3-build]
    uses: ./.github/workflows/ctest.yml
    with:
      cmake_version: 'latest'
      preset_name: ci-StdShar
      file_base: ${{ needs.call-workflow-tarball.outputs.file_base }}
#      use_tag: snapshot
      use_environ: snapshots
    secrets:
        APPLE_CERTS_BASE64: ${{ secrets.APPLE_CERTS_BASE64 }}
        APPLE_CERTS_BASE64_PASSWD: ${{ secrets.APPLE_CERTS_BASE64_PASSWD }}
        KEYCHAIN_PASSWD: ${{ secrets.KEYCHAIN_PASSWD }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_ENDPOINT: ${{ secrets.AZURE_ENDPOINT }}
        AZURE_CODE_SIGNING_NAME: ${{ secrets.AZURE_CODE_SIGNING_NAME }}
        AZURE_CERT_PROFILE_NAME: ${{ secrets.AZURE_CERT_PROFILE_NAME }}
    if: ${{ ((needs.call-workflow-tarball.outputs.has_changes == 'true') || (needs.get-old-names.outputs.run-ignore == 'ignore')) }}

  call-workflow-abi:
    needs: [get-old-names, call-workflow-tarball, call-workflow-ctest]
    uses: ./.github/workflows/abi-report.yml
    with:
      file_ref: '1.14.5'
      file_base: ${{ needs.call-workflow-tarball.outputs.file_base }}
      use_tag: snapshot
      use_environ: snapshots
    if: ${{ ((needs.call-workflow-tarball.outputs.has_changes == 'true') || (needs.get-old-names.outputs.run-ignore == 'ignore')) }}

  call-workflow-release:
    needs: [get-old-names, call-workflow-tarball, call-workflow-ctest, call-workflow-abi]
    permissions:
      contents: write # In order to allow tag creation
    uses: ./.github/workflows/release-files.yml
    with:
      file_base: ${{ needs.call-workflow-tarball.outputs.file_base }}
      file_branch: ${{ needs.call-workflow-tarball.outputs.file_branch }}
      file_sha: ${{ needs.call-workflow-tarball.outputs.file_sha }}
      use_tag: snapshot
      use_environ: snapshots
    if: ${{ ((needs.call-workflow-tarball.outputs.has_changes == 'true') || (needs.get-old-names.outputs.run-ignore == 'ignore')) }}

  call-workflow-remove:
    needs: [get-old-names, call-workflow-tarball, call-workflow-ctest, call-workflow-abi, call-workflow-release]
    permissions:
      contents: write # In order to allow file deletion
    uses: ./.github/workflows/remove-files.yml
    with:
      file_base: ${{ needs.get-old-names.outputs.hdf5-name }}
      use_tag: snapshot
      use_environ: snapshots
    if: ${{ ((needs.call-workflow-tarball.outputs.has_changes == 'true') || (needs.get-old-names.outputs.run-ignore == 'ignore')) && (needs.get-old-names.outputs.hdf5-name != needs.call-workflow-tarball.outputs.file_base) }}

