name: hdf5 dev i386

# Triggers the workflow on a call from another workflow
on:
  workflow_call:
    inputs:
      build_mode:
        description: "release vs. debug build"
        required: true
        type: string

permissions:
  contents: read

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  i386_build_and_test:
    name: "i386 ${{ inputs.build_mode }}"
    runs-on: ubuntu-latest
    steps:
      - name: Get Sources
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: setup alpine
        uses: jirutka/setup-alpine@ae3b3ddba35054804fc4a3507b519fa7e8152050 # v1
        with:
          arch: x86
          packages: >
            build-base
            libaec-dev
            libgit2-dev
            cmake

      - name: Configure
        shell: alpine.sh --root {0}
        run: |
          mkdir build
          cd build
          cmake -C ../config/cmake/cacheinit.cmake -G "Unix Makefiles" \
          --log-level=VERBOSE \
          -DCMAKE_BUILD_TYPE=${{ inputs.build_mode }} \
          -DHDF5_ENABLE_ZLIB_SUPPORT:BOOL=OFF \
          -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF \
          -DHDF5_ENABLE_PLUGIN_SUPPORT:BOOL=OFF \
          -DHDF5_BUILD_CPP_LIB:BOOL=OFF \
          -DHDF5_BUILD_FORTRAN:BOOL=OFF \
          -DHDF5_BUILD_JAVA:BOOL=OFF \
          ..

      - name: Build
        shell: alpine.sh --root {0}
        run: |
          cmake --build . --parallel 3 --config ${{ inputs.build_mode }}
        working-directory: build

      - name: Run Tests
        shell: alpine.sh --root {0}
        run: |
          ctest . --parallel 2 -C ${{ inputs.build_mode }}
        working-directory: build
