name: hdf5 publish files in HDF5 folder from branch to S3

# Triggers the workflow on demand
on:
  workflow_dispatch:
    inputs:
      local_dir:
        description: 'HDF5 local directory'
        type: string
        required: true
      target_dir:
        description: 'hdf5 target bucket directory'
        type: string
        required: true

permissions:
  contents: read

jobs:
  publish-tag:
    runs-on: ubuntu-latest
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Get Sources
          uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
          with:
            fetch-depth: 0
            ref: '${{ github.head_ref || github.ref_name }}'

        - name: List files for the space
          run: |
              ls -l ${{ github.workspace }}
              ls ${{ github.workspace }}/HDF5

        - name: Setup AWS CLI
          uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5
          with:
                 aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                 aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                 aws-region: ${{ secrets.AWS_REGION }}

        - name: Sync dir to S3 bucket
          run: |
                aws s3 sync ./HDF5/${{ inputs.local_dir }} s3://${{ secrets.AWS_S3_BUCKET }}/${{ vars.TARGET_PATH }}/${{ inputs.target_dir }}

