name: hdf5 VFD CI main

on:
  workflow_call:
    inputs:
      build_mode:
        description: "Build type (CMAKE_BUILD_TYPE)"
        required: true
        type: string

permissions:
  contents: read

jobs:
  # Test HDF5 VFDs that are always built by default
  #hdf5_vfd_standard:
  #  uses: ./.github/workflows/vfd-standard.yml
  #  with:
  #    build_mode: "${{ inputs.build_mode }}"

  # Test HDF5 MPI I/O VFD
  #hdf5_vfd_mpiio:
  #  uses: ./.github/workflows/vfd-mpiio.yml
  #  with:
  #    build_mode: "${{ inputs.build_mode }}"

  # Test HDF5 Direct VFD
  #hdf5_vfd_direct:
  #  uses: ./.github/workflows/vfd-direct.yml
  #  with:
  #    build_mode: "${{ inputs.build_mode }}"

  # Test HDF5 Mirror VFD
  #hdf5_vfd_mirror:
  #  uses: ./.github/workflows/vfd-mirror.yml
  #  with:
  #    build_mode: "${{ inputs.build_mode }}"

  # Build aws-c-s3 library for ROS3 VFD testing
  build_aws_c_s3:
    uses: ./.github/workflows/build-aws-c-s3.yml
    with:
      build_mode: "${{ inputs.build_mode }}"
      aws_c_s3_tag: "main"

  # Test HDF5 ROS3 VFD
  hdf5_vfd_ros3:
    needs: build_aws_c_s3
    uses: ./.github/workflows/vfd-ros3.yml
    with:
      build_mode: "${{ inputs.build_mode }}"
      aws_c_s3_build_type: "source"

  # Test HDF5 HDFS VFD
  #hdf5_vfd_hdfs:
  #  uses: ./.github/workflows/vfd-hdfs.yml
  #  with:
  #    build_mode: "${{ inputs.build_mode }}"

  # Test HDF5 Subfiling VFD
  hdf5_vfd_subfiling:
    uses: ./.github/workflows/vfd-subfiling.yml
    with:
      build_mode: "${{ inputs.build_mode }}"
