name: hdf5 dev daily build on schedule

# Triggers the workflow on a schedule or on demand
on:
  workflow_dispatch:
  schedule:
    - cron: "6 0 * * *"

permissions:
    contents: write # In order to allow tag creation and file deletion

jobs:
  daily-build:
    uses: ./.github/workflows/daily-build.yml
    with:
      use_ignore: check
    if: "github.repository_owner == 'HDFGroup'"

  call-workflow-publish:
    needs: [daily-build]
    if: ${{ ((needs.daily-build.outputs.has_changes == 'true') && (github.repository_owner == 'HDFGroup')) }}
    runs-on: ubuntu-latest
    steps:
      - name: Get file base name
        id: get-file-base
        run: |
          FILE_NAME_BASE=$(echo "${{ needs.daily-build.outputs.file_base }}")
          echo "FILE_BASE=$FILE_NAME_BASE" >> $GITHUB_OUTPUT

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get Sources
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          ref: '${{ github.head_ref || github.ref_name }}'

      # Get files created by tarball script
      - name: Get doxygen (Linux)
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: docs-doxygen
          path: ${{ github.workspace }}/${{ steps.get-file-base.outputs.FILE_BASE }}.doxygen

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5
        with:
               aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
               aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
               aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync userguide to latest S3 bucket
        run: |
          aws s3 sync ./${{ steps.get-file-base.outputs.FILE_BASE }}.doxygen s3://${{ secrets.AWS_S3_BUCKET }}/documentation/hdf5/latest --delete

